function getInitData() {
    // 排序"loc", "imgSrc", 图片地址  "title", 地址说明 和 "link" 网址
    return {
        "data": [{
                "name": "q",
                "loc": 1,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "w",
                "loc": 2,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "e",
                "loc": 3,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "r",
                "loc": 4,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "t",
                "loc": 5,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "y",
                "loc": 6,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "u",
                "loc": 7,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "i",
                "loc": 8,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "o",
                "loc": 9,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "p",
                "loc": 10,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "a",
                "loc": 11,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "s",
                "loc": 12,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "d",
                "loc": 13,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "f",
                "loc": 14,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "g",
                "loc": 15,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "h",
                "loc": 16,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "j",
                "loc": 17,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "k",
                "loc": 18,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "l",
                "loc": 19,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "z",
                "loc": 20,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "x",
                "loc": 21,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "c",
                "loc": 22,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "v",
                "loc": 23,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "b",
                "loc": 24,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "n",
                "loc": 25,
                "imgSrc": "",
                "title": "",
                "link": "",
            },
            {
                "name": "m",
                "loc": 26,
                "imgSrc": "",
                "title": "",
                "link": "",
            }
        ]
    }
}